[project]
name = "lore-games"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fast-agent-mcp",
]

[project.optional-dependencies]
test = [
    "pytest",
]